### ISSUE TITLE
Support to add extra parameter for task type in job.xml

### ISSUE THREAD

**Issue by XiyangDong** [beakerlib/beakerlib#124]
Currently there is no differentiation in the generated tasks in job.xml that uses different beakerlib phases like rlPhaseStartSetup, rlPhaseStartCleanup and rlPhaseStartTest. 
We want such support to display what kind of task it is so we can filter out the Setup/Cleanup ones that we don't want to represent in our result reporting tools.

**Comment by sopos** [comment]
This is a question to beaker itself rather than beakerlib.

I'm not sure if there is a native field for that supported by beaker. As far as I know you can add an arbitrary parameter (_a params_ attribute) to the individual tasks in the job.xml and then you can use that specific parameter to identify the task type while processing the results. This is basically the way we use to distinguish setup, test, and cleanup tasks in our workflow.

Generally speaking, a task can introduce whatever phases it wants so there cannot be any generic solution. You need to incorporate it into your workflow.

`rlPhaseStartSetup`, `rlPhaseStartCleanup`, and `rlPhaseStartTest` internally translates into `rlPhaseStart "WARN" "$(1:-Setup}"`, `rlPhaseStart "FAIL" "$(1:-Test}"`, and `rlPhaseStart "WARN" "$(1:-Cleanup}"`. That means you can create a custom named phase. Your workflow needs to count with that.
